### ISSUE TITLE
nexus6打补丁失败...........

### ISSUE THREAD

**Issue by IdeaManYu** [liudongmiao/ForceStopGB#12]
基于官方rom,链接:
http://forum.xda-developers.com/nexus-6/development/rom-5-1lightromstock-lmy47e-03-19-2015-t3059493
提取services.jar services.odex boot.oat
反编译没问题,打补丁出现如下信息

patching file services/com/android/server/IntentResolver.smali
Hunk #1 FAILED at 283.
Hunk #2 FAILED at 549.
2 out of 2 hunks FAILED -- saving rejects to file services/com/android/server/IntentResolver.smali.rej
patching file services/com/android/server/am/ActivityManagerService.smali
Hunk #1 FAILED at 2147.
Hunk #2 FAILED at 9496.
Hunk #3 FAILED at 20961.
Hunk #4 FAILED at 29596.
Hunk #5 FAILED at 31628.
Hunk #6 FAILED at 31753.
Hunk #7 FAILED at 59001.
Hunk #8 FAILED at 69747.
Hunk #9 FAILED at 72231.
Hunk #10 FAILED at 72881.
10 out of 10 hunks FAILED -- saving rejects to file services/com/android/server/am/ActivityManagerService.smali.rej
patching file services/com/android/server/am/ActivityStack.smali
Hunk #1 FAILED at 3708.
Hunk #2 FAILED at 5363.
Hunk #3 FAILED at 13490.
3 out of 3 hunks FAILED -- saving rejects to file services/com/android/server/am/ActivityStack.smali.rej
patching file services/com/android/server/am/ActivityStackSupervisor.smali
Hunk #1 FAILED at 7385.
1 out of 1 hunk FAILED -- saving rejects to file services/com/android/server/am/ActivityStackSupervisor.smali.rej
patching file services/com/android/server/am/PreventRunningUtils.smali
patching file services/me/piebridge/PreventRunning.smali
patching file services/me/piebridge/PreventRunningHook.smali

请赐教

**Comment by IdeaManYu** [comment]
稍等我上传services.jar  services.odex  boot.oat  build.prop
烦请您帮我搞定一下可以吗?

**Comment by IdeaManYu** [comment]
http://pan.baidu.com/s/1hrrhELm
麻烦您了!

**Comment by liudongmiao** [comment]
最好附上你解压后的那几个文件，就是失败的文件。

**Comment by liudongmiao** [comment]
我猜测，你安装的不是jdk 8，或者smali/baksmali版本不对，从而导致smali文件是 \r\n 换行符...

**Comment by liudongmiao** [comment]
我下载了以后，打补丁没有任何问题。

**Comment by zyu0090** [comment]
遇到相同问题，同是Nexus6，services.jar很小，反编译的services.odex，出现同样错误代码，一字不差，jdk 8u74 x86环境，smali/baksmali版本为你提供的2.1.0+14。

**Comment by liudongmiao** [comment]
1. 把你执行的命令窗口截图，发我

2. 把这几个文件打包，发我
services/com/android/server/IntentResolver.smali
services/com/android/server/am/ActivityManagerService.smali
services/com/android/server/am/ActivityStack.smali
services/com/android/server/am/ActivityStackSupervisor.smali

以上打包发送就好。

**Comment by liudongmiao** [comment]
主要还是，我不使用winwos。已经修复，请使用新的文档。

@IdeaManYu @zyu0090

**Comment by zyu0090** [comment]
多谢，我再试试。。Gmail最近推送不及时啊。。不知道是不是我把手机弄残了。。。
