### ISSUE TITLE
避免使用 Xposed.log 方法

### ISSUE THREAD

**Issue by CzBiX** [liudongmiao/ForceStopGB#13]
参考作者注释 [XposedBridge.java#L512](https://github.com/rovo89/XposedBridge/blob/art/app/src/main/java/de/robv/android/xposed/XposedBridge.java#L512)

**Comment by liudongmiao** [comment]
嘻嘻，你知道这是为了干什么么？

因为，因为，没有地方可以记录日志，而绝大部分人，都不知道怎么使用 adb 提取日志....即使我使用 logcat 取，也只能取到最近的，而有些调试日志，必须要记下来，到底是阻止运行问题，还是模块不生效等等问题。

当然，有些用户使用补丁方式使用阻止运行，没有这种困扰，因为根本不安装框架....

**Comment by CzBiX** [comment]
可以引导用户使用 [SysLog](https://play.google.com/store/apps/details?id=com.tortel.syslog) 提取日志。

**Comment by liudongmiao** [comment]
不仅仅是提取问题啊，“即使我使用 logcat 取，也只能取到最近的”，这要是这个问题。如果只是取日志的话，现在点报告问题，就会生成日志，把最近的所有日志都存起来；开机也有记录一份日志。

系统没有任何服务，可以过滤日志把它定向到一个地方。logcat 也只是记在缓存之中，过一段时间，新的就会覆盖旧的。我倒是可以写一个这样的服务，不断把日志记到文件里。但是，既然只有 xposed 模式方式有这样的实现，何必不直接使用 xposed 的方式呢？两者权衡，取其轻者。更重要的是，放在xposed日志里，是有人会看的；另外，还有好多时候，用户根本进不到阻止运行里，第三方程序就显得很有必要。

补丁方式不需要的原因很简单，因为不存在兼容性问题，是针对每个ROM专门写的补丁。
