### ISSUE TITLE
Prevent list bug

### ISSUE THREAD

**Issue by DeadneM** [liudongmiao/ForceStopGB#14]
Hi there since 1.3.4 when reboot the phone prevent running do not start properly in fact if i launch PR the prevent list is empty... So i quit the app launch it again and the prevent list is there. 

I thought i cause no problem but if i boot without doing that the PR app think the list is empty and auto-prevent nothing

https://drive.google.com/open?id=0BwCC2VJYgCavX0NpbWFsamh0V28

**Comment by liudongmiao** [comment]
As the prevent list is stored in user app, prevent running-server cannot read it directly.

So you must let your other app or system app to allow prevent running to load it, via content provider, or receiver. Please let prevent running go in your other app.

I may store it in /data/system/prevent.list for auto load prevent list.

**Comment by DeadneM** [comment]
I have copied the prevent.list from /data/data to /data/system with 640 permission and still same problem 

There was no prevent.list file in /data/system before but a prevent log 

 Is there some script line i could add to my init.d script to force prevent running use his prevent list?

**Comment by DeadneM** [comment]
I forgot to mention that I'm on cm12.1 which means android 5.1.1 so the change you made in 1.3.4 are not necessary in lollipop no? It's just for marshmallow?

**Comment by liudongmiao** [comment]
will fixed in next version. please send me an email to get the beta version.

**Comment by DeadneM** [comment]
I've send an email to pr@piebridge.me with mine 

Thanks ☺

**Comment by DeadneM** [comment]
Well great job issue fixed. The prevent list is in /data/system and it is loaded on opening the app 

Thanks
