### ISSUE TITLE
flyme能否在不root不xposed的情况下打补丁？

### ISSUE THREAD

**Issue by renyouguo** [liudongmiao/ForceStopGB#16]
MX2
flyme 4.2.8.2（基于android4.4.4）
由于系统存在root后VPN失效的bug，所以只能以未root的前提操作，也就无法安装xposed。

**Comment by liudongmiao** [comment]
只要你能替换系统文件，或者刷入bootloader就好，不需要root。

但即使这样，我也不倾向给android 4.4制作补丁，所以都没上传相应文档及补丁代码。

**Comment by renyouguo** [comment]
魅族没有解锁的方法……
算了，爸妈用的，就让他们用绿色守护非root模式吧。

**Comment by liudongmiao** [comment]
其实吧，给爸妈用的话，装少量应用，就那么一两个三四个就好，就无所谓唤醒不唤醒了。

**Comment by daya-prac** [comment]
请问 Flyme5 能用补丁包吗

**Comment by liudongmiao** [comment]
补丁包需要单独制作。理论上，不管哪个版本都可以。
但需要自己能root替换包，或者解锁了bootloader (魅族不提供吧？)
