### ISSUE TITLE
2.1.3打开支付宝以及淘宝的时候手机会卡死并且重启

### ISSUE THREAD

**Issue by Bpazy** [liudongmiao/ForceStopGB#20]
Nexus5, cm13

**Comment by Bpazy** [comment]
:flushed: 修复了乐视的问题，结果大家都出了这个问题，2333333

**Comment by liudongmiao** [comment]
请重启以后，点报告问题吧。
我本机，当然是没有这样的问题的。

**Comment by slimx** [comment]
确实存在,支付宝在打开一段时间后闪退

**Comment by liudongmiao** [comment]
闪退以后，请进入阻止运行，点击菜单，选择“报告问题”即可。
没有日志，我是没有办法处理的...

**Comment by liudongmiao** [comment]
帮忙看下这个版本有没有修复，谢谢：
http://pan.baidu.com/s/1nvNAvbV

**Comment by slimx** [comment]
依旧闪退,问题并未解决,已提交日志

**Comment by liudongmiao** [comment]
应用闪退这个锅我不能背...因为确实没有出现阻止运行强行停止它。
据其他网友反映，可能是在系统其它地方没有给他什么权限导致闪退。

**Comment by slimx** [comment]
已允许了所有的权限,在2.11是正常的,从2.12开始的版本才出现问题.我会再检查一下

在 2016年4月7日 上午9:23，Liu DongMiao <notifications@github.com>写道：

**Comment by Bpazy** [comment]
>帮忙看下这个版本有没有修复，谢谢：
http://pan.baidu.com/s/1nvNAvbV

@liudongmiao 没有发现死机重启的问题

**Comment by liudongmiao** [comment]
fix in 36bf053b7b90ae97982d4686d8c0c7db59679386
