### ISSUE TITLE
一个bug

### ISSUE THREAD

**Issue by t123yh** [liudongmiao/ForceStopGB#7]
当“阻止运行”正在后台运行时，正安装的应用将始终被增加至阻止列表，不论“阻止运行”本身是否在阻止列表。一个小小的bug吧，可以在新装应用加入阻止列表时判断是否应该加入。

**Comment by shminer** [comment]
程序本身如果在组织列表 也就没有后台运行一说了

**Comment by liudongmiao** [comment]
是的，这是一个已知问题...故意的。既然你提到了，我就修了吧。
