### ISSUE TITLE
Update indonesian translation

### ISSUE THREAD

**Issue by exodius48** [liudongmiao/ForceStopGB#9]
Here http://rghost.net/6N6Df5Cxt
I can't use github right now, my internet connection very slow. :(

Btw, v1.3.2 always show english, not Indonesian, although i already used  indonesi as system language.

**Comment by liudongmiao** [comment]
Yes, I didn't compile it with Indonesian, as there are 8/67 english language. 
So I removed the Indonesian language in the apk.
